[package]
name = "node"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
jsonrpsee = { version = "=0.24.9", features = ["macros", "server","client"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
